ManageEngine/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from users.views import login_view, index, logout, register, profile, changepwd, profile_update
#from .views import page_not_found
from django.conf.urls import handler404
import idc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # path('index', views.index,name="index"),
    url(r'^login/$', login_view, name='login'),
    path('index', index, name="index"),
    path('logout.html', logout, name="logout"),
    path('register.html', register, name="register"),
    path('profile.html', profile, name='profile'),
    path('profile_update.html', profile_update, name='profile_update'),
    path('changepwd.html', changepwd, name='changepwd'),

    # assets view
    path('idc/', include('idc.urls')),
    path('assets/', include('assets.urls')),

]
#handler404 = page_not_found

assets/urls.py
from django.urls import path
from django.conf.urls import url
from .views import assetinfo

app_name = 'assets'

urlpatterns = [
    url(r'^assetinfo', view=assetinfo, name='assetinfo'),
]

idc/urls.py
from django.urls import path
from django.conf.urls import url
from idc import views


app_name = "idc"

urlpatterns = [
    path('', views.index, name='index',),
    path('index.html', views.index, name='index',),
    url(r'^idcinfo', views.idcinfo, name='idcinfo',),
    url(r'^idcadd', views.idcadd, name='idcadd',),
    url(r'^idcdetail/(\d+)', views.idcdetail, name='idcdetail',),
    url(r'^idcedit', views.idcinfo_edit, name='idcinfo_edit',),
]



assets/models.py
from django.db import models


# Create your models here.

class Assets(models.Model):
    asset_type_choices = (
        ('server', u'物理机'),
        ('server', u'虚拟机'),
    )
    STATUS_CHOICES = (
        ("ok", "ok"),
        ("repair", "repair"),
        ("withdraw", "withdraw"),
    )
    asset_type = models.CharField(verbose_name='资产类型', max_length=64, choices=asset_type_choices, default='server')
    hostname = models.CharField(max_length=32, unique=True)
    idc = models.CharField(verbose_name='机房', max_length=32, unique=True)
    # 电信IP
    tel_ip = models.CharField(max_length=64, null=True, blank=True, verbose_name='电信IP')
    # 联通IP
    uni_ip = models.CharField(max_length=64, null=True, blank=True, verbose_name='联通IP')
    # 移动IP
    mob_ip = models.CharField(max_length=64, null=True, blank=True, verbose_name='移动IP')

    # fqdn_ip4
    internal_ip = models.GenericIPAddressField(max_length=32, verbose_name='内网IP')
    # cpu_model
    cpu_model = models.CharField(max_length=64, null=True, blank=True, verbose_name='CPU 型号')
    # num_cpus
    cpu_count = models.CharField(max_length=32, null=True, verbose_name='CPU 逻辑个数')
    # memory total
    mem_total = models.CharField(max_length=64, null=True, blank=True, verbose_name='总内存MB')
    # os
    os = models.CharField(max_length=128, null=True, blank=True, verbose_name='操作系统')
    # osrelease
    os_version = models.CharField(max_length=16, null=True, blank=True, verbose_name='os版本')

    salt_state = models.TextField(blank=True, verbose_name='salt状态')
    asset_state = models.CharField(max_length=128, default="ok", choices=STATUS_CHOICES, verbose_name="主机状态")

    comment = models.TextField(blank=True, verbose_name="备注")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    mod_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = '主机信息'

    def __str__(self):
        return self.hostname

assets/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import *
from assets.models import Assets, IDC
import datetime


class IdcForm(forms.ModelForm):
    name = forms.CharField(label=u'机房名称', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    idc_flag = forms.CharField(label=u'机房标示', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label=u'机房地址', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    tel_ip = forms.CharField(label=u'电信IP', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}),
                             validators=[validate_ipv4_address])
    uni_ip = forms.CharField(label=u'联通IP',required=False,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    mob_ip = forms.CharField(label=u'移动IP',required=False,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    dns_ip = forms.CharField(label=u'DNS IP',required=True,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    email = forms.EmailField(label=u'邮箱地址', required=False, widget=forms.TextInput(attrs={'class':'form-control'}), validators=[validate_email])
    comment = forms.CharField(label=u'备注',required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model=IDC
        fields=('name','idc_flag','address','tel_ip','uni_ip','mob_ip','dns_ip','email','comment')

    #def __init__(self,*args, **kwargs):
    #    super(IdcForm,self).__init__(*args, **kwargs)
    #    self.fields['add_time']="2018-03-09"
    #    self.fields['mod_time']=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

assets/views.py
from django.shortcuts import render
from assets import models

# Create your views here.

def assetlist(request):
    print("assetlist")
    return None


#@login_required
def assetinfo(request):
    print("assetsinfo")
    the_assets = models.Assets.objects.all()
    return render(request, 'assets/asset_info.html', locals())
    print(the_assets)

templates/assets/asset_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/assets/asset_info.html
{% extends "base.html" %}
{% block title %}
    主机信息
{% endblock %}

{% block breadcrumb  %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>主机信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href={% url 'index' %}></a>
                </li>
                <li>
                    <a>Users</a>
                </li>
                <li class="active">
                    <strong>主机信息</strong>
                </li>
            </ol>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>主机信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <form id="cha" class="form-horizontal" action="{  }" method="GET">
                                {% csrf_token %}
                                <div class="col-md-2"><input type="text" class="form-control" name="name" placeholder="主机名、IP" required></div>
                                <button class="btn btn-sm btn-primary" type="submit">查询</button>

                                                                {% if perms.asset.add_assetinfo %}
                                <a href="{  }" class="btn btn-sm btn-primary ">添加</a>
                                {% endif %}
                            </form>
                            <form id="del_form_asset_all" class="form-horizontal  " action="{}" method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-asset">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>主机名</th>
                                        <th>内网IP</th>
                                        <th>外网IP</th>
                                        <th>内存</th>
                                        <th>cpu核数</th>
                                        <th>操作系统版本</th>
                                        <th>业务</th>
                                        <th>负责人</th>
                                    </tr>
                                    </thead>

                                    {% for   row   in   asset_list.object_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"><a
                                                    href="{   }">{{ row.hostname }}</a>
                                            </td>
                                            <td class="center">{{ row.network_ip }}</td>
                                            <td class="center">{{ row.inner_ip }}</td>
                                            <td class="center">{{ row.platform }} | {{ row.region }}</td>
                                            <td class="center"><div class="label label-primary">{{ row.project }}</div></td>
                                         <td class="center"><div class="label label-success">{{ row.business }}</div></td>
                                            <td class="center"><b>{% ifequal  row.is_active  True %}   <i class="fa fa-check text-navy"></i>{% endifequal %}
                                             {% ifequal   row.is_active  False  %}   <i class="fa fa-times text-danger"></i> {% endifequal %} </b>
                                            </td>
                                            <td><a class="btn btn-primary  btn-xs "
                                                   href="{}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  asset_del">删除</a>
                                            <a type="button" class="btn btn-success btn-xs webssh">终端
                                            </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>
                                <a class="btn btn-sm btn-danger  asset_all_del">批量删除</a>
                                <button class="btn btn-sm btn-primary" type="submit">导出</button>
                                <a href="{}" class="btn btn-sm btn-primary ">导出全部</a>
                                <a href="{}"  class="btn btn-sm btn-primary ">导入</a>


  <div style="text-align:center;">
<nav class="pagination">


         <li><a href="{}?page=1">首页 </a></li>

            {% if asset_list.has_previous %}
                <li class="long"><a href="?{{ asset_list.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}

            {% for page in asset_list.pages %}
            {% if page %}
                {% ifequal page asset_list.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                     <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="none"><a href="">...</a></li>
            {% endif %}
            {% endfor %}
            {% if asset_list.has_next %}
                <li class="long"><a href="?{{ asset_list.next_page_number.querystring }}">下一页</a></li>
            {% endif %}
  <li>
                                                <a href="{}?page={{ asset_list.paginator.num_pages }}">尾页 </a>
                                            </li>
                                            <li><span style="color: #0a0a0a">总: &nbsp;{{ asset_list.paginator.num_pages }} 页 </span>
                                            </li>

</nav>
  </div>





                            </form>


                        </div>

                    </div>


                </div>
            </div>
{% endblock %}

templates/assets/idc_add.html
{% extends "base.html" %}
{% block title %}
    IDC|新增机房
{% endblock %}

{% block breadcrumb  %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>user management</h2>
            <ol class="breadcrumb">
                <li>
                    <a href={% url 'index' %}></a>
                </li>
                <li>
                    <a>Users</a>
                </li>
                <li class="active">
                    <strong>增加机房</strong>
                </li>
            </ol>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
<form class="form-horizontal" role="form" method="POST" action={% url 'asset:idcadd' %} xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-md-2 control-label">机房名字</label>
        <div class="col-md-4">{{ form.name }}{{ form.name.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">机房标示</label>
        <div class="col-md-3">{{ form.idc_flag }}{{ form.idc_flag.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">机房地址</label>
        <div class="col-md-4">{{ form.address }}{{ form.address.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">电信IP</label>
        <div class="col-md-4">{{ form.tel_ip }}{{ form.tel_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">联通IP</label>
        <div class="col-md-4">{{ form.uni_ip }}{{ form.uni_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">移动IP</label>
        <div class="col-md-4">{{ form.mob_ip }}{{ form.mob_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">DNS IP</label>
        <div class="col-md-4">{{ form.dns_ip}}{{ form.dns_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Email</label>
        <div class="col-md-4">{{ form.email }}{{ form.email.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">备注</label>
        <div class="col-md-4">{{ form.comment }}{{ form.comment.errors }}</div>
    </div>

    <div class="form-group">
        <div class="col-sm-10 col-md-offset-2 controls-row">
            <button type="submit" class="btn btn-success btn-outline m-b">增加</button>
            <a href={% url 'asset:assetinfo' %} class="btn btn-warning btn-outline m-b">取 消</a>
        </div>
    </div>
</form>
    </div>
    </div>
{% endblock %}
{% block footjs %}
<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
{% endblock %}