ManageEngine/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from users.views import login_view, index, logout, register, profile, changepwd, profile_update
#from .views import page_not_found
from django.conf.urls import handler404
import idc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # path('index', views.index,name="index"),
    url(r'^login/$', login_view, name='login'),
    path('index', index, name="index"),
    path('logout.html', logout, name="logout"),
    path('register.html', register, name="register"),
    path('profile.html', profile, name='profile'),
    path('profile_update.html', profile_update, name='profile_update'),
    path('changepwd.html', changepwd, name='changepwd'),

    # assets view
    path('idc/', include('idc.urls')),
    path('assets/', include('assets.urls')),

]
#handler404 = page_not_found

assets/urls.py
from django.urls import path
from django.conf.urls import url
from .views import assetinfo

app_name = 'assets'

urlpatterns = [
    url(r'^assetinfo', view=assetinfo, name='assetinfo'),
]

idc/urls.py
from django.urls import path
from django.conf.urls import url
from idc import views


app_name = "idc"

urlpatterns = [
    path('', views.index, name='index',),
    path('index.html', views.index, name='index',),
    url(r'^idcinfo', views.idcinfo, name='idcinfo',),
    url(r'^idcadd', views.idcadd, name='idcadd',),
    url(r'^idcdetail/(\d+)', views.idcdetail, name='idcdetail',),
    url(r'^idcedit', views.idcinfo_edit, name='idcinfo_edit',),
]



templates/base.html

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}ManageEngine | 控制面板{% endblock %}</title>

    {% include 'head_css.html' %}{% block headcss %}{% endblock %}

    <!-- 引入css -->
    <script type="text/javascript" src="/static/app/js/jquery-2.1.1.js"></script>
    <!-- <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.1.min.js"></script> -->
    <script type="text/javascript" src="/static/app/js/bootstrap.js"></script>

</head>

<body>
    <div  id="wrapper">

        <!--zuo ce bian lan kaishi -->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span>
                                {% if user.headimg %}
                                    <img alt="image" class="img-circle" src="/{{ user.headimg }}" width="40" height="40"/>
                                {% else %}
                                    <img alt="image" class="img-circle" src="/static/images/touxiang/tou.gif" width="40" height="40"/>
                                {% endif %}
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">{{ user.username }}</strong>
                                    </span>
                                    <span class="text-muted text-xs block">
                                        {% if user.is_superuser %}
                                            管理员
                                        {% else %}
                                            普通用户
                                        {% endif %}
                                        <b class="caret"></b>
                                    </span>
                                </span>
                            </a>
                            <ul class="dropdown-menu animate fadeInRight m-t-xs">
                                <li><a href={% url 'profile' %}>profile</a></li>
                                <li><a href={% url 'changepwd'  %}>change password</li>
                                {% if user.is_superuser %}
                                    <!--  <li><a>user management</a></li> -->
                                    <li><a href="">group management</a></li>
                                {% endif %}
                            </ul>

                        </div>
                        <div class="logo-element">
                            {% if user.headimg %}
                                <img alt="image" class="img-circle" src="/{{ user.headimg }}" width="40" height="40"/>
                            {% else %}
                                <img alt="image" class="img-circle" src="/static/images/touxiang/tou.gif" width="40" height="40"/>
                            {% endif %}
                        </div>
                    </li>
                    <li>
                        <a href="{% url "index" %}"><i class="fa fa-home"></i> <span class="nav-label">首页</span></a>
                    </li>
                    <li class="{{ assset_active }}">
                        <a href="#"><i class="fa fa-inbox"></i>  <span class="nav-label">资产管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li class="{{ asset_list_active }}"><a href="{% url 'assets:assetinfo' %} }">资产信息</a></li>
                            <li class="{{ asset_user_list_active }}"><a href="{  }">资产用户</a></li>
                            <li class="{{ asset_project_list_active }}"><a href="{  }">资产项目</a></li>
                            <li class="{{ asset_business_list_active }}"><a href="{  }">资产业务</a></li>
                            <li class="{{ asset_idc_info_active }}"><a href="{% url 'idc:idcinfo' %}">机房信息</a></li>
                        </ul>
                    </li>

                    <li class="{{ tasks_active }}">
                        <a href="#"><i class="fa  fa-coffee"></i> <span class="nav-label">作业中心</span><span class="fa arrow"> </span></a>
                    <ul class="nav nav-second-level">
                        <li class="{{ tasks_cmd_active }}"><a href="{  }">命令操作</a></li>
                        <li class="{{ tasks_tail_active }}"><a href="{     }">日志接口</a></li>
                        <li class="{{ tools_active }}"><a href="{ }">脚本工具</a></li>
                        <li class="{{ vars_active }}"><a href="{ }">主机变量</a></li>
                        <li class="{{ tools_exec_active }}"><a href="{}">创建任务</a></li>
                        <li class="{{ tools_results_active }}"><a href="{}">任务结果</a></li>
                    </ul>
                    </li>

                </ul>
            </div>
        </nav>
        <!-- zuo ce bian lan jieshu -->


        <div id="page-wrapper" class="gray-bg">
            <!-- top kaishi-->
            <div class="row border-bottom">
                {% block navbar %}
                    <nav class="navbar navbar-static-top white" role="navigation" style="margin-bottom: 0">
                {% endblock %}
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i>
                    </a>
                    <form role="search" class="navbar-form-custom" action={% url 'index' %}>
                       <div class="form-group">
                           <input type="text" placeholder="search" class="form-control" name="top-search" id="top-search">
                       </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Welcom {{ username }} to ME</span>
                        </li>


                        <!-- yi ge tu biao -->
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i><span class="label label-warning">0</span>
                            </a>
                            <!--xia la caidan  -->
                            <ul class="dropdown-menu dropdown-messages">

                                <li>
                                    <div class="dropdown-messages-box">
                                        <a href="#" class="pull-left"><img alt="image" class="img-circle" src="/static/images/Linux.png"></a>
                                        <div>
                                            <small class="pull-right">46h ago</small>
                                            <strong>Mike Loreipsum</strong>started followimg<strong>Monica Smith</strong> <br>
                                            <small class="text-muted">3 days ago</small>
                                        </div>

                                    </div>
                                </li>

                                <li class="divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a href="#" class="pull-left">
                                            <img alt="image" class="img-circle" src="/static/images/touxiang/tou.gif">
                                        </a>
                                        <div>
                                            <small class="pull-right text-navy">5 hours ago</small>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <!--xia la caidan end-->
                        </li>
                        <!-- yi ge tu biao  end--->

                        <!-- second icon_begin-->
                        <li class="dropdown" id="alert">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i><span class="label label-primary" id="count-info-num">3</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="#">
                                        <div><i class="fa fa-envelope fa-fw"></i>You have 16 messages
                                            <span class="pull-right text-muted small"></span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- second icon end -->

                        <li>
                            <a href="/logout.html">
                                <i class="fa fa-sign-out"></i> 登 出
                            </a>
                        </li>

                </ul>

            </div>
            <!-- top  end-->


            {% block breadcrumb %}
            {% endblock %}

            {% block content %}
            {% endblock %}

            <div class="footer">
                <div class="pull-right">
                    版本号: <strong>0.1.0</strong>(2018.2.6)
                </div>
                <div>
                    <strong>Copyright</strong> ME platform &copy; 2018
                </div>
            </div>
        </div>
    </div>


    <!-- Mainly scripts -->
    {% include 'foot_js.html' %}
    {% block footjs %}
    {% endblock %}


</body>
</html>

templates/error.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ME | 500 错误</title>

    <link href="/static/app/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/app/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/app/css/animate.css" rel="stylesheet">
    <link href="/static/app/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>错误</h1>
        <h3 class="font-bold text-danger">{{ message }}</h3>
        <h3 id="jumpTo" class="font-bold text-info"></h3>
        <div class="error-desc">
            抱歉,你所访问的请求出现了错误!<br/>
            请返回: <br/><a href={% url 'index' %} class="btn btn-primary m-t">首页</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/static/app/js/jquery-2.1.1.js"></script>
    <script src="/static/app/js/bootstrap.min.js"></script>

</body>
<script>
    function countDown(secs,surl){
         var jumpTo = document.getElementById('jumpTo');
         jumpTo.innerHTML= secs + '秒' + '后返回上一页';
         if(--secs>0){
             setTimeout("countDown("+secs+",'"+surl+"')",1000);
             }
         else{
             location.href=surl;
             }
         }
    countDown(5,document.referrer);
</script>
</html>

templates/foot_js.html

<script src="http://libs.baidu.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>




    <!-- Sparkline -->
{#<script src="/static/app/js/plugins/sparkline/jquery.sparkline.min.js"></script>#}

templates/head_css.html
<link rel="shortcut icon" type="image/x-icon" href="/static/images/Linux.png" />

<link href="/static/app/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/app/font-awesome/css/font-awesome.css" rel="stylesheet">

<link href="/static/app/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="/static/app/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="/static/app/css/plugins/dataTables/datatables.min.css" rel="stylesheet">
<link href="/static/app/css/plugins/footable/footable.core.css" rel="stylesheet">
<link href="/static/app/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
<link href="/static/app/css/plugins/cropper/cropper.min.css" rel="stylesheet">
<link href="/static/app/css/plugins/select2/select2.min.css" rel="stylesheet">
<link href="/static/app/css/plugins/ladda/ladda-themeless.min.css" rel="stylesheet">


<link href="/static/app/css/animate.css" rel="stylesheet">

<link href="/static/app/css/plugins/dropzone/basic.css" rel="stylesheet">
<link href="/static/app/css/plugins/dropzone/dropzone.css" rel="stylesheet">
<link href="/static/app/css/plugins/codemirror/codemirror.css" rel="stylesheet">
<link href="/static/app/css/plugins/codemirror/ambiance.css" rel="stylesheet">
<link href="/static/app/css/plugins/summernote/summernote.css" rel="stylesheet">
<link href="/static/app/css/plugins/summernote/summernote-bs3.css" rel="stylesheet">
<link href="/static/app/css/style.css" rel="stylesheet">

<link href="/static/app/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>

hello world!
</body>
</html>

templates/perm_deny.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Permission denied</title>

    <link href="/static/app/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/app/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/app/css/animate.css" rel="stylesheet">
    <link href="/static/app/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>抱歉</h1>
        <h2 class="font-bold">没有权限</h2>
        <h3>
            对不起,你没有权限访问这个页面,请联系网站管理员以获取权限
        </h3>

        <div class="error-desc">
            <br/>
            回首页以继续: <br/><a href="/" class="btn btn-primary m-t">首页</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/static/app/js/jquery-2.1.1.js"></script>
    <script src="/static/app/js/bootstrap.min.js"></script>

</body>

</html>

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ME | Success</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/app/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/app/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/app/css/animate.css" rel="stylesheet">
    <link href="/static/app/css/style.css" rel="stylesheet">
</head>
<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>成功</h1>
        <h3 class="font-bold">{{ msg }}</h3>

        <div class="error-desc">
            <br/>
            回首页以继续: <br/><a href="/" class="btn btn-primary m-t">首页</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/static/app/js/jquery-2.1.1.js"></script>
    <script src="/static/app/js/bootstrap.min.js"></script>

</body>
</html>