ManageEngine/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from users.views import login_view, index, logout, register, profile, changepwd, profile_update
#from .views import page_not_found
from django.conf.urls import handler404
import idc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # path('index', views.index,name="index"),
    url(r'^login/$', login_view, name='login'),
    path('index', index, name="index"),
    path('logout.html', logout, name="logout"),
    path('register.html', register, name="register"),
    path('profile.html', profile, name='profile'),
    path('profile_update.html', profile_update, name='profile_update'),
    path('changepwd.html', changepwd, name='changepwd'),

    # assets view
    path('idc/', include('idc.urls')),
    path('assets/', include('assets.urls')),

]
#handler404 = page_not_found

idc/urls.py
from django.urls import path
from django.conf.urls import url
from idc import views


app_name = "idc"

urlpatterns = [
    path('', views.index, name='index',),
    path('index.html', views.index, name='index',),
    url(r'^idcinfo', views.idcinfo, name='idcinfo',),
    url(r'^idcadd', views.idcadd, name='idcadd',),
    url(r'^idcdetail/(\d+)', views.idcdetail, name='idcdetail',),
    url(r'^idcedit', views.idcinfo_edit, name='idcinfo_edit',),
]



idc/models.py
from django.db import models


# Create your models here.


class IDC(models.Model):
    name = models.CharField(max_length=32, verbose_name="机房名",unique=True,help_text="机房名")
    idc_flag = models.CharField(max_length=32,verbose_name="机房标识",unique=True)
    address = models.CharField(max_length=128, null=True,blank=True,verbose_name="机房地址",help_text="机房地址")
    tel_ip = models.CharField(max_length=64,null=True,blank=True,verbose_name="电信IP段",help_text="电线IP段")
    mob_ip = models.CharField(max_length=64,null=True,blank=True,verbose_name="移动IP段",help_text="移动IP段")
    uni_ip = models.CharField(max_length=64,null=True,blank=True,verbose_name="联通IP段",help_text="联通IP段")
    dns_ip = models.CharField(max_length=64,null=True,blank=True,verbose_name="DNS",help_text="DNS")
    email = models.EmailField(verbose_name="email地址")
    comment = models.TextField(blank=True,verbose_name="备注",help_text="备注")
    #首次添加时间
    add_time = models.DateTimeField(auto_now_add=True,verbose_name="添加时间",help_text="添加时间")
    #修改时间
    mod_time = models.DateTimeField(auto_now=True,verbose_name="修改时间",help_text="修改时间")

    class Meta:
        verbose_name="IDC机房"
        verbose_name_plural=verbose_name

    def __str__(self):
        return 'id:%s name:%s' %(self.id, self.name)



idc/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import *
from idc.models import  IDC
import datetime


class IdcForm(forms.ModelForm):
    name = forms.CharField(label=u'机房名称', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    idc_flag = forms.CharField(label=u'机房标示', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label=u'机房地址', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    tel_ip = forms.CharField(label=u'电信IP', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}),
                             validators=[validate_ipv4_address])
    uni_ip = forms.CharField(label=u'联通IP',required=False,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    mob_ip = forms.CharField(label=u'移动IP',required=False,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    dns_ip = forms.CharField(label=u'DNS IP',required=True,widget=forms.TextInput(attrs={'class': 'form-control'}), validators=[validate_ipv4_address])
    email = forms.EmailField(label=u'邮箱地址', required=False, widget=forms.TextInput(attrs={'class':'form-control'}), validators=[validate_email])
    comment = forms.CharField(label=u'备注',required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model=IDC
        fields=('name','idc_flag','address','tel_ip','uni_ip','mob_ip','dns_ip','email','comment')

    #def __init__(self,*args, **kwargs):
    #    super(IdcForm,self).__init__(*args, **kwargs)
    #    self.fields['add_time']="2018-03-09"
    #    self.fields['mod_time']=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')





idc/views.py
# Create your views here.

from django.contrib.auth.decorators import login_required
from idc import models
from idc.forms import IdcForm
from django.shortcuts import render_to_response, HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from idc.models import IDC
import json

def idcdetail(request, func):
    if request.method == 'GET':
        print(type(func))
        obj = models.IDC.objects.get(id=func)
        print("enter idcdetail")
        return render(request, 'idc/../templates/assets/asset_detail.html', locals())


def page_not_found(request):
    return render_to_response("404.html")


def index(request):
    print("index")
    return render_to_response("404.html")


# 展示机房信息
def idcinfo(request):
    idc_info = models.IDC.objects.all()
    return render(request, 'idc/idc_info.html', locals())


# 新增机房
def idcadd(request):
    form = IdcForm()
    if request.method == "POST":
        form = IdcForm(request.POST)
        print(form)
        if form.is_valid():
            # form_data = form.cleaned_data
            # print(form_data)
            # new_idc_obj = models.IDC(**form_data)
            # new_idc_obj.save()
            form.save()
            return HttpResponseRedirect('idcinfo/')
    else:
        form = IdcForm()
    return render(request, 'idc/idc_add.html', locals())


# 编辑机房信息
def idcedit(request):
    print("idc edit")
    print(id)
    return None


# 机房信息编辑
def idcinfo_edit(request):
    id = int(request.POST.get('id'))
    idc_info = IDC.objects.get(id=id)
    if request.method == 'POST':
        form = IdcForm(request.POST,instance=idc_info)
        if form.is_valid():
            try:
                form.save()
                return HttpResponse('yes')
            except:
                return HttpResponse('no')
        else:
            return HttpResponse('no')
    #return render(request,'idc/idc_info.html',locals())


templates/idc/idc_add.html
{% extends "base.html" %}
{% block title %}
    IDC|新增机房
{% endblock %}

{% block breadcrumb  %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>user management</h2>
            <ol class="breadcrumb">
                <li>
                    <a href={% url 'index' %}></a>
                </li>
                <li>
                    <a>Users</a>
                </li>
                <li class="active">
                    <strong>增加机房</strong>
                </li>
            </ol>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
<form class="form-horizontal" role="form" method="POST" action={% url 'idc:idcadd' %} xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-md-2 control-label">机房名字</label>
        <div class="col-md-4">{{ form.name }}{{ form.name.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">机房标示</label>
        <div class="col-md-3">{{ form.idc_flag }}{{ form.idc_flag.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">机房地址</label>
        <div class="col-md-4">{{ form.address }}{{ form.address.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">电信IP</label>
        <div class="col-md-4">{{ form.tel_ip }}{{ form.tel_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">联通IP</label>
        <div class="col-md-4">{{ form.uni_ip }}{{ form.uni_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">移动IP</label>
        <div class="col-md-4">{{ form.mob_ip }}{{ form.mob_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">DNS IP</label>
        <div class="col-md-4">{{ form.dns_ip}}{{ form.dns_ip.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Email</label>
        <div class="col-md-4">{{ form.email }}{{ form.email.errors }}</div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">备注</label>
        <div class="col-md-4">{{ form.comment }}{{ form.comment.errors }}</div>
    </div>

    <div class="form-group">
        <div class="col-sm-10 col-md-offset-2 controls-row">
            <button type="submit" class="btn btn-success btn-outline m-b">增加</button>
            <a href={% url 'idc:idcinfo' %} class="btn btn-warning btn-outline m-b">取 消</a>
        </div>
    </div>
</form>
    </div>
    </div>
{% endblock %}
{% block footjs %}
<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
{% endblock %}

templates/idc/t_layui.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>开始使用layui</title>
  <link rel="stylesheet" href="/static/layui/css/layui.css">
</head>
<body>

<!-- 你的HTML代码 -->

<script src="/static/layui/layui.js"></script>
<script>
//一般直接写在一个js文件中
layui.use(['layer', 'form'], function(){
  var layer = layui.layer
  ,form = layui.form;

  layer.msg('Hello World');
});
</script>
</body>
</html>